## Futuchain whitepaper & roadmap (work in progress - contracts not out yet, don't fall for scams please)

Establishing a new level of web governance by entering into international agreements with projects of high value for the rebirth of an IOT 3.0 

## The DAO

FUTUCHAIN Decentralize collaborations between individuals and companies, simplifying their connection through partnership services and facilitations for token governance holders (FUTU)

## Problem

Solve the lack of decentralized connections between individuals and companies, give greater possibility to connect freely and anonymously in any place and time to companies and individuals open to collaborations and partnerships. 


## Solution

Create a network of contacts between different sectors able to interact autonomously in the community and raise funds in a decentralized way thanks to the technology of the ERC-20 futuchain contract $FUTU. Equity token holders will be able to actively participate in the dao benefiting from all the facilities and partnerships, choosing whether to remain anonymous thanks to the security of the DeFi. Creators will be able to get in direct contact with investors by taking advantage of the IC internet conjoiner protocol, a platform that will list several projects that can be published through the purchase of FUTU tokens, thus becoming a token governance holder having the opportunity to take advantage of partnership and funding services.

```markdown
futuristic conjoiner
aggregator of prominent characters
ensuring a future at all times in history

```

## Eco

Futuchain: $FUTU=DeFi (erc 20)

$RIST: semi decentralized(bsc)

Futuchan: online community

Internet conjoiner: collection of liquidity pools projects

## Tokens

### $FUTU

Tokenomics $FUTU 

Total 7000000000 FUTU

Development fund portfolio 
1% of each transfer or exchange is added to futuristic engine's development portfolio 

Waigoing capital duty By selling $FUTU, you will pay an exit fee of 10% of your sale, this percentage goes into a pool of liquidity dedicated to future airdrops and more development of the ecosystem. Giving up your governance token before the airdrop has been made will result in a loss of capital, only FUTU active addresses will receive the monthly airdrops.

### $RICO

Total 1000000000000000 $RICO

Tokenomics $RICO

Liquidity growth 5% of each transfer or transaction is permanently added to liquidity 

Development fund portfolio 5% of each transfer or exchange is added to futuristic engine's development portfolio 

Frictionless yield holders of $RICO earn a passive income of 5% through static reflection 

## IC Pools

1 - You swap ETH for FUTU, making so you are investing in futuchain

2 - We deeply search for new awesome projects and partnerships

3 - We proceed to show the most valuable ones to the community

4 - Investors can now choose among the projects and vote for the best ones. We will make pools available based on the projects score after the vote is done. 

5 - You can now stake your FUTU chosen pair and earn LP rewards while supporting the project. (Also remember that if you change your mind you can always claim back your committed ETH in every moment, just swap your tokens for ETH on your favourite DEX).

6 - Now that your FUTU is sitting in your preferred pair pool with no locking period, you can claim your liquidity provider rewards overtime, you can choose to compound all in the same pool or hold the tokens reward in to your wallet, you can claim more governance presence swapping ETH for FUTU on your favourite DEX and stake those in more project active pools or just hold in your wallet for the monthly airdrops.

7 - The projects have now access to more liquidity to improve development and advertise, this will lead to more visibility to bring more investors in and make them aware of the complete ecosystem. This will also affect your rewards and have a strong impact on the APR.

8 - Also every listed project is an holder of the equity token FUTU. 
This is for both creators and investors: The more FUTU you stake (or is staked) in your pool of choice, the more score the project gets. 

## Partnership

Each partner that will become an equity token holder will offer and also receive facilities from the other major holders who are members of the community. We thought of a great network of connections for every field, from restaurants, hotels, transport to shops and brands. Only FUTU knows what the future holds for us.

—

## ROADMAP: 

```markdown
### 1 - Genesis 
•Creation of official owner website 
•Social networks, communities and web presence 
•social rICO announcement


### 2 - First come first served 
•reversible ICO (rICO)
•campaign on social profiles to announce the launch of the token that will take place on pancake swap 
•social contest + random aidrop of tokens $RICO to participants 

### 3 - Futu~Rico 
•first partnerships 
•adding more $FUTU liquidity 
•improvements to the website •monthly aidrop$ $FUTU

### 4 - Futuristic engine 
•Presentation of the IC internet conjoiner platform and publication of first projects and partnerships 
•(NFTs) 
•Launch of pools to invest directly in projects on the internet conjoiner using $RICO token

### 5 - Futuchan 
•nft presentation of artists from the Futuchain Futuchan community 
•Launch first nfts

### 6 - Internal Conjoined
•events and meetings with project creators and community members 
•Minting event tickets to certify episodes and keep representative NFTs forever 

### 7 - The futuristic conjoiner 
•reduction of the transaction tax to 0.5% 
•waiver of the contract 
•complete decentralization 
```


## FUTUCHAIN in a nutshell: 

### Futuchain 
is the name of the DAO and name of the blockchain 

### (the) Futuristic conjoiner
is the motto/incipit 

### FUTUCHAN
the given name to the online community

### FUTU 
is the governance token (equivalent of an equity token) ERC-20 circuit (until the completion of the blockchain)

### RICO 
is the initial reversible ico / utility token (lowest fees and fastest transactions) BSC Binance Smart Chain (until the completion of the blockchain) 

### IC
internet conjoiner is an aggregator of high-value projects and investors, it also allows you to collect liquidity through $FUTU token in a decentralized way allowing you to make changes to the investment at any time without blocked funds. 

### You can only stake $FUTU pairs in liquidity for IC projects. 

## For the creators

### Propose your projects and join the ecosystem!

1 - First you’ll need your personal token to make possible for investir to provide liquidity  in a DeFi way. 

2 - We accept and will always accept only audited tokens and eventually proceed to create a fresh one for your project’s pool.

3 - Stake FUTU tokens in tue pool and provide liquidity to set the price for the tokens pair and you are ready to start claiming your first LP rewards, more liquidity from investors and also gaining visibility thanks to the IC (Internet conjoiner) project’s pool score leaderboard

4 - Fill the form on the official website to be selected! You don’t have to buy FUTU tokens yet* but you can do it at any time if you want to support futuchain developement!

*Major holders are not gaining score as the IC pools do, instead they are elegible to all the facilities offered by our partners. 



```markdown
ensuring a future at all times in history
```

```markdown
### Support or Contact

[reddit](https://www.reddit.com/r/futuchain/)

[twitter](https://twitter.com/futuchain/)

[telegram announcements](https://t.me/futuchain/)

[telegram community](https://t.me/futuchan/)
```

